# Run configs
set ::env(PDK_ROOT) {/home/kareem_farid/caravel/deps/openlane-new/pdk}
set ::env(BASE_SDC_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {1}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_PERIOD) {50}
set ::env(CLOCK_PORT) {serial_clock}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl lvs.tcl}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CVC_SCRIPTS_DIR) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/cvc}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_fd_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/home/kareem_farid/caravel/openlane/gpio_control_block/config.tcl}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {gpio_control_block}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0 0 170 65}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {4}
set ::env(DIODE_PADDING) {0}
set ::env(DPL_CELL_PADDING) {0}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/drc_exclude_list.txt}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/kareem_farid/caravel/openlane/gpio_control_block/drc_exclude_list.txt}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(EXTRA_GDS_FILES) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../gds/gpio_logic_high.gds}
set ::env(EXTRA_LEFS) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../lef/gpio_logic_high.lef}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FILL_INSERTION) {1}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_DEF_TEMPLATE) {/home/kareem_farid/caravel/openlane/gpio_control_block/template/gpio_control_block.def}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {0}
set ::env(FP_PDN_CHECK_NODES) {0}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {1.5}
set ::env(FP_PDN_HORIZONTAL_HALO) {0}
set ::env(FP_PDN_HPITCH) {20}
set ::env(FP_PDN_HSPACING) {3.4}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_MACRO_HOOKS) { gpio_logic_high vccd1 vssd1 vccd1 vssd1}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_SKIPTRIM) {1}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {0}
set ::env(FP_PDN_VOFFSET) {9.0}
set ::env(FP_PDN_VPITCH) {25}
set ::env(FP_PDN_VSPACING) {3.4}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {2}
set ::env(FP_TAP_VERTICAL_HALO) {2}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.025}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NETS) {vssd vssd1}
set ::env(GND_PIN) {VGND}
set ::env(GPIO_PADS_LEF) { /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_VERILOG) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/verilog/sky130_fd_io/sky130_ef_io.v}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.05}
set ::env(GRT_ALLOW_CONGESTION) {0}
set ::env(GRT_ANT_ITERS) {3}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAXLAYER) {4}
set ::env(GRT_MAX_DIODE_INS_ITERS) {1}
set ::env(GRT_MINLAYER) {2}
set ::env(GRT_OBS) { 
	li1 0 0 16.79500 30.02500,
	li1 0 29.96500 4.26500 65.07000,
	li1 4.21500 57.40500 49.81500 64.93000,
	li1 16.83000 0 49.41000 5.24000,
	li1 49.000 0 169.81000 64.84500,
	met5 50 0 170 65,
	met4 49 0 170 65,
	met2 120 0 170 65,
	met1 120 0 170 65}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/drc/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {10}
set ::env(LIB_FASTEST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_SLOWEST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_TYPICAL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MACRO_PLACEMENT_CFG) {/home/kareem_farid/caravel/openlane/gpio_control_block/macro_placement.cfg}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_NO_DEF_BLOCKAGES) {1}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(NETGEN_SETUP_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(PDKPATH) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A}
set ::env(PDN_CFG) {/home/kareem_farid/caravel/openlane/gpio_control_block/pdn.tcl}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_LIB) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {1}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {1}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {0}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {0}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.95}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.calibre}
set ::env(RCX_RULES_MAX) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.calibre}
set ::env(RCX_RULES_MIN) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.calibre}
set ::env(REPORTS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports}
set ::env(RESULTS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {256}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {2}
set ::env(RSZ_DONT_TOUCH) {user_gpio_out user_gpio_oeb serial_clock_out serial_load_out gpio_defaults*}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50}
set ::env(RUN_DRT) {1}
set ::env(RUN_IRDROP_REPORT) {1}
set ::env(RUN_KLAYOUT) {1}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {1}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SIMPLE_CTS) {0}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_TAG) {22_10_18_13_50}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(START_TIME) {2022.10.18_20.50.18}
set ::env(STA_REPORT_POWER) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {0}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/yosys_mapping.v}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {10}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {1}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(SYNTH_TOP_LEVEL) {0}
set ::env(SYNTH_USE_PG_PINS_DEFINES) {USE_POWER_PINS}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TAP_DECAP_INSERTION) {1}
set ::env(TECH_LEF) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp}
set ::env(TOP_MARGIN_MULT) {1}
set ::env(TRACKS_INFO_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRISTATE_BUFFER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(UNBUFFER_NETS) {^$}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VDD_NETS) {vccd vccd1}
set ::env(VDD_PIN) {VPWR}
set ::env(VERILOG_FILES) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/defines.v /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/gpio_control_block.v}
set ::env(VERILOG_FILES_BLACKBOX) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/gpio_logic_high.v}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(cts_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/cts}
set ::env(cts_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/cts}
set ::env(cts_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/cts}
set ::env(cts_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/cts}
set ::env(eco_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/eco}
set ::env(eco_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/eco}
set ::env(eco_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/eco}
set ::env(eco_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/eco}
set ::env(floorplan_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/floorplan}
set ::env(floorplan_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/floorplan}
set ::env(floorplan_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/floorplan}
set ::env(floorplan_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/floorplan}
set ::env(placement_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/placement}
set ::env(placement_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/placement}
set ::env(placement_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/placement}
set ::env(placement_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/placement}
set ::env(routing_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/routing}
set ::env(routing_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/routing}
set ::env(routing_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing}
set ::env(routing_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing}
set ::env(signoff_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/signoff}
set ::env(signoff_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/signoff}
set ::env(signoff_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/signoff}
set ::env(signoff_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff}
set ::env(synthesis_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/synthesis}
set ::env(synthesis_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/synthesis}
set ::env(synthesis_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/synthesis}
set ::env(synthesis_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(CURRENT_DEF) /home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.def
set ::env(CURRENT_GUIDE) /home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/23-global.guide
set ::env(CURRENT_INDEX) 41
set ::env(CURRENT_NETLIST) /home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff/36-powered_netlist.v
set ::env(PREV_NETLIST) /home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/25-detailed.v
set ::env(PDK_ROOT) {/home/kareem_farid/caravel/deps/openlane-new/pdk}
set ::env(ANTENNA_VIOLATOR_LIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/signoff/41-antenna_violators.rpt}
set ::env(BASE_SDC_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/base.sdc}
set ::env(BASIC_PREP_COMPLETE) {1}
set ::env(BOTTOM_MARGIN_MULT) {1}
set ::env(CARAVEL_ROOT) {/home/kareem_farid/caravel}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {serial_clock}
set ::env(CLOCK_PERIOD) {50}
set ::env(CLOCK_PORT) {serial_clock}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl lvs.tcl}
set ::env(CORE_AREA) {4.6 2.72 51.98 59.84}
set ::env(CORE_HEIGHT) {57.12}
set ::env(CORE_WIDTH) {47.38}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CURRENT_DEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.def}
set ::env(CURRENT_GDS) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/signoff/gpio_control_block.gds}
set ::env(CURRENT_GUIDE) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/23-global.guide}
set ::env(CURRENT_INDEX) {41}
set ::env(CURRENT_NETLIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff/36-powered_netlist.v}
set ::env(CURRENT_SDC) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/17-resizer_timing.sdc}
set ::env(CURRENT_SDF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.sdf}
set ::env(CURRENT_SPEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.nom.spef}
set ::env(CVC_SCRIPTS_DIR) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/cvc}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_fd_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/home/kareem_farid/caravel/openlane/gpio_control_block/config.tcl}
set ::env(DESIGN_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {gpio_control_block}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0.0 0.0 170.0 65.0}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {4}
set ::env(DIODE_PADDING) {0}
set ::env(DONT_USE_CELLS) { sky130_fd_sc_hd__clkdlybuf4s15_1 sky130_fd_sc_hd__clkdlybuf4s18_1 sky130_fd_sc_hd__lpflow_bleeder_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_16 sky130_fd_sc_hd__lpflow_clkbufkapwr_2 sky130_fd_sc_hd__lpflow_clkbufkapwr_4 sky130_fd_sc_hd__lpflow_clkbufkapwr_8 sky130_fd_sc_hd__lpflow_clkinvkapwr_1 sky130_fd_sc_hd__lpflow_clkinvkapwr_16 sky130_fd_sc_hd__lpflow_clkinvkapwr_2 sky130_fd_sc_hd__lpflow_clkinvkapwr_4 sky130_fd_sc_hd__lpflow_clkinvkapwr_8 sky130_fd_sc_hd__lpflow_decapkapwr_12 sky130_fd_sc_hd__lpflow_decapkapwr_3 sky130_fd_sc_hd__lpflow_decapkapwr_4 sky130_fd_sc_hd__lpflow_decapkapwr_6 sky130_fd_sc_hd__lpflow_decapkapwr_8 sky130_fd_sc_hd__lpflow_inputiso0n_1 sky130_fd_sc_hd__lpflow_inputiso0p_1 sky130_fd_sc_hd__lpflow_inputiso1n_1 sky130_fd_sc_hd__lpflow_inputiso1p_1 sky130_fd_sc_hd__lpflow_inputisolatch_1 sky130_fd_sc_hd__lpflow_isobufsrc_1 sky130_fd_sc_hd__lpflow_isobufsrc_16 sky130_fd_sc_hd__lpflow_isobufsrc_2 sky130_fd_sc_hd__lpflow_isobufsrc_4 sky130_fd_sc_hd__lpflow_isobufsrc_8 sky130_fd_sc_hd__lpflow_isobufsrckapwr_16 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4  }
set ::env(DPL_CELL_PADDING) {0}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/drc_exclude_list.txt}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/kareem_farid/caravel/openlane/gpio_control_block/drc_exclude_list.txt}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(EXTRA_GDS_FILES) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../gds/gpio_logic_high.gds}
set ::env(EXTRA_LEFS) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../lef/gpio_logic_high.lef}
set ::env(EXT_NETLIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/signoff/gpio_control_block.spice}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FILL_INSERTION) {1}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_DEF_TEMPLATE) {/home/kareem_farid/caravel/openlane/gpio_control_block/template/gpio_control_block.def}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {0}
set ::env(FP_PDN_CHECK_NODES) {0}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {1.5}
set ::env(FP_PDN_HORIZONTAL_HALO) {0}
set ::env(FP_PDN_HPITCH) {20}
set ::env(FP_PDN_HSPACING) {3.4}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_MACRO_HOOKS) { gpio_logic_high vccd1 vssd1 vccd1 vssd1}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_SKIPTRIM) {1}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {0}
set ::env(FP_PDN_VOFFSET) {9.0}
set ::env(FP_PDN_VPITCH) {25}
set ::env(FP_PDN_VSPACING) {3.4}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {2}
set ::env(FP_TAP_VERTICAL_HALO) {2}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.025}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NET) {vssd}
set ::env(GND_NETS) {vssd vssd1}
set ::env(GND_PIN) {vssd}
set ::env(GPIO_PADS_LEF) { /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_VERILOG) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/verilog/sky130_fd_io/sky130_ef_io.v}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.05}
set ::env(GRT_ALLOW_CONGESTION) {0}
set ::env(GRT_ANT_ITERS) {3}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAXLAYER) {4}
set ::env(GRT_MAX_DIODE_INS_ITERS) {1}
set ::env(GRT_MINLAYER) {2}
set ::env(GRT_OBS) { 
	li1 0 0 16.79500 30.02500,
	li1 0 29.96500 4.26500 65.07000,
	li1 4.21500 57.40500 49.81500 64.93000,
	li1 16.83000 0 49.41000 5.24000,
	li1 49.000 0 169.81000 64.84500,
	met5 50 0 170 65,
	met4 49 0 170 65,
	met2 120 0 170 65,
	met1 120 0 170 65}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(HOME) {/}
set ::env(HOSTNAME) {418daf2eb26e}
set ::env(INPUT_DEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff/36-powered_def.def}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/drc/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LANG) {en_US.UTF-8}
set ::env(LAST_TIMING_REPORT_TAG) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/signoff/32-rcx_sta}
set ::env(LC_ALL) {en_US.UTF-8}
set ::env(LC_CTYPE) {en_US.UTF-8}
set ::env(LD_LIBRARY_PATH) {/build//lib:/build//lib/Linux-x86_64:}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {10}
set ::env(LIB_CTS) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/cts/cts.lib}
set ::env(LIB_FASTEST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_RESIZER_OPT) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis/resizer_sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SLOWEST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis/trimmed.lib}
set ::env(LIB_SYNTH_COMPLETE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SYNTH_COMPLETE_NO_PG) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis/2-sky130_fd_sc_hd__tt_025C_1v80.no_pg.lib}
set ::env(LIB_SYNTH_MERGED) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis/merged.lib}
set ::env(LIB_SYNTH_NO_PG) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis/2-trimmed.no_pg.lib}
set ::env(LIB_TYPICAL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MACRO_PLACEMENT_CFG) {/home/kareem_farid/caravel/openlane/gpio_control_block/macro_placement.cfg}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GDS) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/signoff/gpio_control_block.magic.gds}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_NO_DEF_BLOCKAGES) {1}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(MAGTYPE) {maglef}
set ::env(MANPATH) {/build//share/man:}
set ::env(MAX_METAL_LAYER) {6}
set ::env(MERGED_LEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/merged.nom.lef}
set ::env(MERGED_LEF_MAX) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/merged.max.lef}
set ::env(MERGED_LEF_MIN) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/merged.min.lef}
set ::env(MISMATCHES_OK) {1}
set ::env(NETGEN_SETUP_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OPENLANE_ROOT) {/openlane}
set ::env(OPENLANE_RUN_TAG) {22_10_18_13_50}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(OPENLANE_VERSION) {37faafee20ec76a349fb817d7a75ed26d94be904}
set ::env(OPENROAD) {/build/}
set ::env(OPENROAD_BIN) {openroad}
set ::env(PATH) {/openlane:/openlane/scripts:/build//bin:/build//bin/Linux-x86_64:/build//pdn/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
set ::env(PDK) {sky130A}
set ::env(PDKPATH) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A}
set ::env(PDK_ROOT) {/home/kareem_farid/caravel/deps/openlane-new/pdk}
set ::env(PDN_CFG) {/home/kareem_farid/caravel/openlane/gpio_control_block/pdn.tcl}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_INIT_COEFF) {0.00002}
set ::env(PL_IO_ITER) {5}
set ::env(PL_LIB) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {1}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {1}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {0}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {0}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.95}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PREV_NETLIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/25-detailed.v}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(PWD) {/home/kareem_farid/caravel/openlane}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_LEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/merged.nom.lef}
set ::env(RCX_LIB) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.calibre}
set ::env(RCX_RULESET) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.calibre}
set ::env(RCX_RULES_MAX) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.calibre}
set ::env(RCX_RULES_MIN) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.calibre}
set ::env(REPORTS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports}
set ::env(RESULTS_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {256}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {2}
set ::env(RSZ_DONT_TOUCH) {user_gpio_out user_gpio_oeb serial_clock_out serial_load_out gpio_defaults*}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50}
set ::env(RUN_DRT) {1}
set ::env(RUN_IRDROP_REPORT) {1}
set ::env(RUN_KLAYOUT) {1}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {1}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SIMPLE_CTS) {0}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_STANDALONE) {1}
set ::env(RUN_TAG) {22_10_18_13_50}
set ::env(SAVE_DEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.def}
set ::env(SAVE_GUIDE) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/23-global.guide}
set ::env(SAVE_NETLIST) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff/36-powered_netlist.v}
set ::env(SAVE_SDC) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/17-resizer_timing.sdc}
set ::env(SAVE_SDF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.sdf}
set ::env(SAVE_SPEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block.nom.spef}
set ::env(SCRIPTS_DIR) {/openlane/scripts}
set ::env(SHLVL) {1}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(SPEF_PREFIX) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing/gpio_control_block}
set ::env(START_TIME) {2022.10.18_20.50.18}
set ::env(STA_LEF) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/merged.nom.lef}
set ::env(STA_PRE_CTS) {0}
set ::env(STA_REPORT_POWER) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {0}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DEFINES) {USE_POWER_PINS}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {/home/kareem_farid/caravel/openlane/gpio_control_block/yosys_mapping.v}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {10}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_OPT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {1}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(SYNTH_TOP_LEVEL) {0}
set ::env(SYNTH_USE_PG_PINS_DEFINES) {USE_POWER_PINS}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TAP_DECAP_INSERTION) {1}
set ::env(TCLLIBPATH) {/usr/share/tcl8.5 /usr/lib64/tcl8.5 /usr/lib64/tk8.5 /usr/share/tk8.5 /openlane/scripts/ /usr/share/tcl8.5/tcllib-1.14}
set ::env(TECH_LEF) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_METAL_LAYERS) {li1 met1 met2 met3 met4 met5}
set ::env(TERM) {xterm}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp}
set ::env(TOP_MARGIN_MULT) {1}
set ::env(TRACKS_INFO_FILE) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRACKS_INFO_FILE_PROCESSED) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing/config.tracks}
set ::env(TRISTATE_BUFFER_MAP) {/home/kareem_farid/caravel/deps/openlane-new/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(UNBUFFER_NETS) {serial_clock_out_buffered|serial_load_out_buffered}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VCHECK_OUTPUT) {The version of open_pdks used in building the PDK does not match the version OpenLane was tested on (installed: de752ec0ba4da0ecb1fbcd309eeec4993d88f5bc, tested: fa87f8f4bbcc7255b6f0c0fb506960f531ae2392)
This may introduce some issues. You may want to re-install the PDK by invoking `make pdk`.}
set ::env(VDD_NET) {vccd}
set ::env(VDD_NETS) {vccd vccd1}
set ::env(VDD_PIN) {vccd}
set ::env(VERILOG_FILES) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/defines.v /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/gpio_control_block.v}
set ::env(VERILOG_FILES_BLACKBOX) { /home/kareem_farid/caravel/openlane/gpio_control_block/../../verilog/rtl/gpio_logic_high.v}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(_) {/openlane/flow.tcl}
set ::env(cts_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/cts}
set ::env(cts_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/cts}
set ::env(cts_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/cts}
set ::env(cts_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/cts}
set ::env(drc_prefix) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/signoff/drc}
set ::env(eco_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/eco}
set ::env(eco_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/eco}
set ::env(eco_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/eco}
set ::env(eco_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/eco}
set ::env(floorplan_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/floorplan}
set ::env(floorplan_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/floorplan}
set ::env(floorplan_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/floorplan}
set ::env(floorplan_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/floorplan}
set ::env(fp_report_prefix) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/floorplan/3-initial_fp}
set ::env(placement_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/placement}
set ::env(placement_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/placement}
set ::env(placement_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/placement}
set ::env(placement_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/placement}
set ::env(routing_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/routing}
set ::env(routing_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/routing}
set ::env(routing_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/routing}
set ::env(routing_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/routing}
set ::env(signoff_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/signoff}
set ::env(signoff_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/signoff}
set ::env(signoff_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/signoff}
set ::env(signoff_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/signoff}
set ::env(synth_report_prefix) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/synthesis/2-synthesis}
set ::env(synthesis_logs) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/logs/synthesis}
set ::env(synthesis_reports) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/reports/synthesis}
set ::env(synthesis_results) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/results/synthesis}
set ::env(synthesis_tmpfiles) {/home/kareem_farid/caravel/openlane/gpio_control_block/runs/22_10_18_13_50/tmp/synthesis}
set ::env(timer_end) {1666126300}
set ::env(timer_start) {1666126218}
