/* Generated by Yosys 0.20+70 (git sha1 6e907acf86d, gcc 8.3.1 -fPIC -Os) */

module gpio_signal_buffering(vccd, vssd, mgmt_io_in_unbuf, mgmt_io_out_unbuf, mgmt_io_oeb_buf, mgmt_io_in_buf, mgmt_io_out_buf, mgmt_io_oeb_unbuf);
  wire \buf_in[0] ;
  wire \buf_in[100] ;
  wire \buf_in[101] ;
  wire \buf_in[102] ;
  wire \buf_in[103] ;
  wire \buf_in[104] ;
  wire \buf_in[105] ;
  wire \buf_in[106] ;
  wire \buf_in[107] ;
  wire \buf_in[108] ;
  wire \buf_in[109] ;
  wire \buf_in[10] ;
  wire \buf_in[110] ;
  wire \buf_in[111] ;
  wire \buf_in[112] ;
  wire \buf_in[113] ;
  wire \buf_in[114] ;
  wire \buf_in[115] ;
  wire \buf_in[116] ;
  wire \buf_in[117] ;
  wire \buf_in[118] ;
  wire \buf_in[119] ;
  wire \buf_in[11] ;
  wire \buf_in[120] ;
  wire \buf_in[121] ;
  wire \buf_in[122] ;
  wire \buf_in[123] ;
  wire \buf_in[124] ;
  wire \buf_in[125] ;
  wire \buf_in[126] ;
  wire \buf_in[127] ;
  wire \buf_in[128] ;
  wire \buf_in[129] ;
  wire \buf_in[12] ;
  wire \buf_in[130] ;
  wire \buf_in[131] ;
  wire \buf_in[132] ;
  wire \buf_in[133] ;
  wire \buf_in[134] ;
  wire \buf_in[135] ;
  wire \buf_in[136] ;
  wire \buf_in[137] ;
  wire \buf_in[138] ;
  wire \buf_in[139] ;
  wire \buf_in[13] ;
  wire \buf_in[140] ;
  wire \buf_in[141] ;
  wire \buf_in[142] ;
  wire \buf_in[143] ;
  wire \buf_in[144] ;
  wire \buf_in[145] ;
  wire \buf_in[146] ;
  wire \buf_in[147] ;
  wire \buf_in[148] ;
  wire \buf_in[149] ;
  wire \buf_in[14] ;
  wire \buf_in[150] ;
  wire \buf_in[151] ;
  wire \buf_in[152] ;
  wire \buf_in[153] ;
  wire \buf_in[154] ;
  wire \buf_in[155] ;
  wire \buf_in[156] ;
  wire \buf_in[157] ;
  wire \buf_in[158] ;
  wire \buf_in[159] ;
  wire \buf_in[15] ;
  wire \buf_in[160] ;
  wire \buf_in[161] ;
  wire \buf_in[162] ;
  wire \buf_in[163] ;
  wire \buf_in[164] ;
  wire \buf_in[165] ;
  wire \buf_in[166] ;
  wire \buf_in[167] ;
  wire \buf_in[168] ;
  wire \buf_in[169] ;
  wire \buf_in[16] ;
  wire \buf_in[170] ;
  wire \buf_in[171] ;
  wire \buf_in[172] ;
  wire \buf_in[173] ;
  wire \buf_in[174] ;
  wire \buf_in[175] ;
  wire \buf_in[176] ;
  wire \buf_in[177] ;
  wire \buf_in[178] ;
  wire \buf_in[179] ;
  wire \buf_in[17] ;
  wire \buf_in[180] ;
  wire \buf_in[181] ;
  wire \buf_in[182] ;
  wire \buf_in[183] ;
  wire \buf_in[184] ;
  wire \buf_in[185] ;
  wire \buf_in[186] ;
  wire \buf_in[187] ;
  wire \buf_in[188] ;
  wire \buf_in[189] ;
  wire \buf_in[18] ;
  wire \buf_in[190] ;
  wire \buf_in[191] ;
  wire \buf_in[192] ;
  wire \buf_in[193] ;
  wire \buf_in[194] ;
  wire \buf_in[195] ;
  wire \buf_in[19] ;
  wire \buf_in[1] ;
  wire \buf_in[20] ;
  wire \buf_in[21] ;
  wire \buf_in[22] ;
  wire \buf_in[23] ;
  wire \buf_in[24] ;
  wire \buf_in[25] ;
  wire \buf_in[26] ;
  wire \buf_in[27] ;
  wire \buf_in[28] ;
  wire \buf_in[29] ;
  wire \buf_in[2] ;
  wire \buf_in[30] ;
  wire \buf_in[31] ;
  wire \buf_in[32] ;
  wire \buf_in[33] ;
  wire \buf_in[34] ;
  wire \buf_in[35] ;
  wire \buf_in[36] ;
  wire \buf_in[37] ;
  wire \buf_in[38] ;
  wire \buf_in[39] ;
  wire \buf_in[3] ;
  wire \buf_in[40] ;
  wire \buf_in[41] ;
  wire \buf_in[42] ;
  wire \buf_in[43] ;
  wire \buf_in[44] ;
  wire \buf_in[45] ;
  wire \buf_in[46] ;
  wire \buf_in[47] ;
  wire \buf_in[48] ;
  wire \buf_in[49] ;
  wire \buf_in[4] ;
  wire \buf_in[50] ;
  wire \buf_in[51] ;
  wire \buf_in[52] ;
  wire \buf_in[53] ;
  wire \buf_in[54] ;
  wire \buf_in[55] ;
  wire \buf_in[56] ;
  wire \buf_in[57] ;
  wire \buf_in[58] ;
  wire \buf_in[59] ;
  wire \buf_in[5] ;
  wire \buf_in[60] ;
  wire \buf_in[61] ;
  wire \buf_in[62] ;
  wire \buf_in[63] ;
  wire \buf_in[64] ;
  wire \buf_in[65] ;
  wire \buf_in[66] ;
  wire \buf_in[67] ;
  wire \buf_in[68] ;
  wire \buf_in[69] ;
  wire \buf_in[6] ;
  wire \buf_in[70] ;
  wire \buf_in[71] ;
  wire \buf_in[72] ;
  wire \buf_in[73] ;
  wire \buf_in[74] ;
  wire \buf_in[75] ;
  wire \buf_in[76] ;
  wire \buf_in[77] ;
  wire \buf_in[78] ;
  wire \buf_in[79] ;
  wire \buf_in[7] ;
  wire \buf_in[80] ;
  wire \buf_in[81] ;
  wire \buf_in[82] ;
  wire \buf_in[83] ;
  wire \buf_in[84] ;
  wire \buf_in[85] ;
  wire \buf_in[86] ;
  wire \buf_in[87] ;
  wire \buf_in[88] ;
  wire \buf_in[89] ;
  wire \buf_in[8] ;
  wire \buf_in[90] ;
  wire \buf_in[91] ;
  wire \buf_in[92] ;
  wire \buf_in[93] ;
  wire \buf_in[94] ;
  wire \buf_in[95] ;
  wire \buf_in[96] ;
  wire \buf_in[97] ;
  wire \buf_in[98] ;
  wire \buf_in[99] ;
  wire \buf_in[9] ;
  wire \buf_out[0] ;
  wire \buf_out[100] ;
  wire \buf_out[101] ;
  wire \buf_out[102] ;
  wire \buf_out[103] ;
  wire \buf_out[104] ;
  wire \buf_out[105] ;
  wire \buf_out[106] ;
  wire \buf_out[107] ;
  wire \buf_out[108] ;
  wire \buf_out[109] ;
  wire \buf_out[10] ;
  wire \buf_out[110] ;
  wire \buf_out[111] ;
  wire \buf_out[112] ;
  wire \buf_out[113] ;
  wire \buf_out[114] ;
  wire \buf_out[115] ;
  wire \buf_out[116] ;
  wire \buf_out[117] ;
  wire \buf_out[118] ;
  wire \buf_out[119] ;
  wire \buf_out[11] ;
  wire \buf_out[120] ;
  wire \buf_out[121] ;
  wire \buf_out[122] ;
  wire \buf_out[123] ;
  wire \buf_out[124] ;
  wire \buf_out[125] ;
  wire \buf_out[126] ;
  wire \buf_out[127] ;
  wire \buf_out[128] ;
  wire \buf_out[129] ;
  wire \buf_out[12] ;
  wire \buf_out[130] ;
  wire \buf_out[131] ;
  wire \buf_out[132] ;
  wire \buf_out[133] ;
  wire \buf_out[134] ;
  wire \buf_out[135] ;
  wire \buf_out[136] ;
  wire \buf_out[137] ;
  wire \buf_out[138] ;
  wire \buf_out[139] ;
  wire \buf_out[13] ;
  wire \buf_out[140] ;
  wire \buf_out[141] ;
  wire \buf_out[142] ;
  wire \buf_out[143] ;
  wire \buf_out[144] ;
  wire \buf_out[145] ;
  wire \buf_out[146] ;
  wire \buf_out[147] ;
  wire \buf_out[148] ;
  wire \buf_out[149] ;
  wire \buf_out[14] ;
  wire \buf_out[150] ;
  wire \buf_out[151] ;
  wire \buf_out[152] ;
  wire \buf_out[153] ;
  wire \buf_out[154] ;
  wire \buf_out[155] ;
  wire \buf_out[156] ;
  wire \buf_out[157] ;
  wire \buf_out[158] ;
  wire \buf_out[159] ;
  wire \buf_out[15] ;
  wire \buf_out[160] ;
  wire \buf_out[161] ;
  wire \buf_out[162] ;
  wire \buf_out[163] ;
  wire \buf_out[164] ;
  wire \buf_out[165] ;
  wire \buf_out[166] ;
  wire \buf_out[167] ;
  wire \buf_out[168] ;
  wire \buf_out[169] ;
  wire \buf_out[16] ;
  wire \buf_out[170] ;
  wire \buf_out[171] ;
  wire \buf_out[172] ;
  wire \buf_out[173] ;
  wire \buf_out[174] ;
  wire \buf_out[175] ;
  wire \buf_out[176] ;
  wire \buf_out[177] ;
  wire \buf_out[178] ;
  wire \buf_out[179] ;
  wire \buf_out[17] ;
  wire \buf_out[180] ;
  wire \buf_out[181] ;
  wire \buf_out[182] ;
  wire \buf_out[183] ;
  wire \buf_out[184] ;
  wire \buf_out[185] ;
  wire \buf_out[186] ;
  wire \buf_out[187] ;
  wire \buf_out[188] ;
  wire \buf_out[189] ;
  wire \buf_out[18] ;
  wire \buf_out[190] ;
  wire \buf_out[191] ;
  wire \buf_out[192] ;
  wire \buf_out[193] ;
  wire \buf_out[194] ;
  wire \buf_out[195] ;
  wire \buf_out[19] ;
  wire \buf_out[1] ;
  wire \buf_out[20] ;
  wire \buf_out[21] ;
  wire \buf_out[22] ;
  wire \buf_out[23] ;
  wire \buf_out[24] ;
  wire \buf_out[25] ;
  wire \buf_out[26] ;
  wire \buf_out[27] ;
  wire \buf_out[28] ;
  wire \buf_out[29] ;
  wire \buf_out[2] ;
  wire \buf_out[30] ;
  wire \buf_out[31] ;
  wire \buf_out[32] ;
  wire \buf_out[33] ;
  wire \buf_out[34] ;
  wire \buf_out[35] ;
  wire \buf_out[36] ;
  wire \buf_out[37] ;
  wire \buf_out[38] ;
  wire \buf_out[39] ;
  wire \buf_out[3] ;
  wire \buf_out[40] ;
  wire \buf_out[41] ;
  wire \buf_out[42] ;
  wire \buf_out[43] ;
  wire \buf_out[44] ;
  wire \buf_out[45] ;
  wire \buf_out[46] ;
  wire \buf_out[47] ;
  wire \buf_out[48] ;
  wire \buf_out[49] ;
  wire \buf_out[4] ;
  wire \buf_out[50] ;
  wire \buf_out[51] ;
  wire \buf_out[52] ;
  wire \buf_out[53] ;
  wire \buf_out[54] ;
  wire \buf_out[55] ;
  wire \buf_out[56] ;
  wire \buf_out[57] ;
  wire \buf_out[58] ;
  wire \buf_out[59] ;
  wire \buf_out[5] ;
  wire \buf_out[60] ;
  wire \buf_out[61] ;
  wire \buf_out[62] ;
  wire \buf_out[63] ;
  wire \buf_out[64] ;
  wire \buf_out[65] ;
  wire \buf_out[66] ;
  wire \buf_out[67] ;
  wire \buf_out[68] ;
  wire \buf_out[69] ;
  wire \buf_out[6] ;
  wire \buf_out[70] ;
  wire \buf_out[71] ;
  wire \buf_out[72] ;
  wire \buf_out[73] ;
  wire \buf_out[74] ;
  wire \buf_out[75] ;
  wire \buf_out[76] ;
  wire \buf_out[77] ;
  wire \buf_out[78] ;
  wire \buf_out[79] ;
  wire \buf_out[7] ;
  wire \buf_out[80] ;
  wire \buf_out[81] ;
  wire \buf_out[82] ;
  wire \buf_out[83] ;
  wire \buf_out[84] ;
  wire \buf_out[85] ;
  wire \buf_out[86] ;
  wire \buf_out[87] ;
  wire \buf_out[88] ;
  wire \buf_out[89] ;
  wire \buf_out[8] ;
  wire \buf_out[90] ;
  wire \buf_out[91] ;
  wire \buf_out[92] ;
  wire \buf_out[93] ;
  wire \buf_out[94] ;
  wire \buf_out[95] ;
  wire \buf_out[96] ;
  wire \buf_out[97] ;
  wire \buf_out[98] ;
  wire \buf_out[99] ;
  wire \buf_out[9] ;
  output [30:0] mgmt_io_in_buf;
  wire [30:0] mgmt_io_in_buf;
  input [30:0] mgmt_io_in_unbuf;
  wire [30:0] mgmt_io_in_unbuf;
  output [2:0] mgmt_io_oeb_buf;
  wire [2:0] mgmt_io_oeb_buf;
  input [2:0] mgmt_io_oeb_unbuf;
  wire [2:0] mgmt_io_oeb_unbuf;
  output [30:0] mgmt_io_out_buf;
  wire [30:0] mgmt_io_out_buf;
  input [30:0] mgmt_io_out_unbuf;
  wire [30:0] mgmt_io_out_unbuf;
  input vccd;
  wire vccd;
  input vssd;
  wire vssd;
  sky130_fd_sc_hd__buf_8 \signal_buffers[0]  (
    .A(mgmt_io_in_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[0] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[100]  (
    .A(mgmt_io_out_unbuf[5]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[100] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[101]  (
    .A(mgmt_io_out_unbuf[6]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[102] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[102]  (
    .A(\buf_in[102] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[102] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[103]  (
    .A(mgmt_io_out_unbuf[7]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[104] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[104]  (
    .A(\buf_in[104] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[104] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[105]  (
    .A(mgmt_io_out_unbuf[8]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[106] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[106]  (
    .A(\buf_in[106] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[107] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[107]  (
    .A(\buf_in[107] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[107] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[108]  (
    .A(mgmt_io_out_unbuf[9]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[109] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[109]  (
    .A(\buf_in[109] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[110] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[10]  (
    .A(mgmt_io_in_unbuf[8]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[11] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[110]  (
    .A(\buf_in[110] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[110] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[111]  (
    .A(mgmt_io_out_unbuf[10]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[112] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[112]  (
    .A(\buf_in[112] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[113] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[113]  (
    .A(\buf_in[113] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[113] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[114]  (
    .A(mgmt_io_out_unbuf[11]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[115] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[115]  (
    .A(\buf_in[115] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[116] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[116]  (
    .A(\buf_in[116] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[117] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[117]  (
    .A(\buf_in[117] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[117] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[118]  (
    .A(mgmt_io_out_unbuf[12]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[119] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[119]  (
    .A(\buf_in[119] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[120] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[11]  (
    .A(\buf_in[11] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[12] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[120]  (
    .A(\buf_in[120] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[121] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[121]  (
    .A(\buf_in[121] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[122] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[122]  (
    .A(\buf_in[122] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[123] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[123]  (
    .A(\buf_in[123] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[123] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[124]  (
    .A(mgmt_io_out_unbuf[13]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[125] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[125]  (
    .A(\buf_in[125] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[126] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[126]  (
    .A(\buf_in[126] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[127] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[127]  (
    .A(\buf_in[127] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[128] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[128]  (
    .A(\buf_in[128] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[129] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[129]  (
    .A(\buf_in[129] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[129] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[12]  (
    .A(\buf_in[12] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[12] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[130]  (
    .A(mgmt_io_out_unbuf[14]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[131] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[131]  (
    .A(\buf_in[131] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[132] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[132]  (
    .A(\buf_in[132] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[133] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[133]  (
    .A(\buf_in[133] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[134] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[134]  (
    .A(\buf_in[134] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[135] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[135]  (
    .A(\buf_in[135] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[135] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[136]  (
    .A(mgmt_io_out_unbuf[15]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[137] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[137]  (
    .A(\buf_in[137] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[138] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[138]  (
    .A(\buf_in[138] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[139] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[139]  (
    .A(\buf_in[139] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[140] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[13]  (
    .A(mgmt_io_in_unbuf[9]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[14] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[140]  (
    .A(\buf_in[140] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[140] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[141]  (
    .A(mgmt_io_out_unbuf[16]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[142] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[142]  (
    .A(\buf_in[142] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[143] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[143]  (
    .A(\buf_in[143] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[144] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[144]  (
    .A(\buf_in[144] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[145] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[145]  (
    .A(\buf_in[145] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[145] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[146]  (
    .A(mgmt_io_out_unbuf[17]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[147] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[147]  (
    .A(\buf_in[147] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[148] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[148]  (
    .A(\buf_in[148] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[149] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[149]  (
    .A(\buf_in[149] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[149] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[14]  (
    .A(\buf_in[14] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[15] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[150]  (
    .A(mgmt_io_out_unbuf[18]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[151] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[151]  (
    .A(\buf_in[151] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[152] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[152]  (
    .A(\buf_in[152] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[153] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[153]  (
    .A(\buf_in[153] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[153] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[154]  (
    .A(mgmt_io_out_unbuf[19]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[155] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[155]  (
    .A(\buf_in[155] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[156] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[156]  (
    .A(\buf_in[156] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[157] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[157]  (
    .A(\buf_in[157] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[157] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[158]  (
    .A(mgmt_io_out_unbuf[20]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[159] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[159]  (
    .A(\buf_in[159] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[160] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[15]  (
    .A(\buf_in[15] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[15] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[160]  (
    .A(\buf_in[160] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[161] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[161]  (
    .A(\buf_in[161] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[161] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[162]  (
    .A(mgmt_io_out_unbuf[21]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[163] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[163]  (
    .A(\buf_in[163] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[164] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[164]  (
    .A(\buf_in[164] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[165] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[165]  (
    .A(\buf_in[165] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[165] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[166]  (
    .A(mgmt_io_out_unbuf[22]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[167] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[167]  (
    .A(\buf_in[167] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[168] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[168]  (
    .A(\buf_in[168] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[169] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[169]  (
    .A(\buf_in[169] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[169] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[16]  (
    .A(mgmt_io_in_unbuf[10]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[17] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[170]  (
    .A(mgmt_io_out_unbuf[23]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[171] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[171]  (
    .A(\buf_in[171] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[172] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[172]  (
    .A(\buf_in[172] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[172] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[173]  (
    .A(mgmt_io_out_unbuf[24]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[174] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[174]  (
    .A(\buf_in[174] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[175] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[175]  (
    .A(\buf_in[175] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[175] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[176]  (
    .A(mgmt_io_out_unbuf[25]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[177] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[177]  (
    .A(\buf_in[177] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[178] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[178]  (
    .A(\buf_in[178] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[178] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[179]  (
    .A(mgmt_io_out_unbuf[26]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[180] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[17]  (
    .A(\buf_in[17] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[18] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[180]  (
    .A(\buf_in[180] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[181] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[181]  (
    .A(\buf_in[181] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[181] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[182]  (
    .A(mgmt_io_out_unbuf[27]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[183] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[183]  (
    .A(\buf_in[183] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[183] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[184]  (
    .A(mgmt_io_out_unbuf[28]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[185] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[185]  (
    .A(\buf_in[185] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[185] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[186]  (
    .A(mgmt_io_out_unbuf[29]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[187] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[187]  (
    .A(\buf_in[187] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[187] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[188]  (
    .A(mgmt_io_out_unbuf[30]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[189] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[189]  (
    .A(\buf_in[189] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[189] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[18]  (
    .A(\buf_in[18] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[18] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[190]  (
    .A(mgmt_io_oeb_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[191] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[191]  (
    .A(\buf_in[191] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[191] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[192]  (
    .A(mgmt_io_oeb_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[193] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[193]  (
    .A(\buf_in[193] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[193] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[194]  (
    .A(mgmt_io_oeb_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[195] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[195]  (
    .A(\buf_in[195] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[195] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[19]  (
    .A(mgmt_io_in_unbuf[11]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[20] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[1]  (
    .A(mgmt_io_in_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[1] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[20]  (
    .A(\buf_in[20] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[21] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[21]  (
    .A(\buf_in[21] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[22] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[22]  (
    .A(\buf_in[22] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[22] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[23]  (
    .A(mgmt_io_in_unbuf[12]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[24] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[24]  (
    .A(\buf_in[24] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[25] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[25]  (
    .A(\buf_in[25] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[26] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[26]  (
    .A(\buf_in[26] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[27] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[27]  (
    .A(\buf_in[27] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[28] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[28]  (
    .A(\buf_in[28] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[28] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[29]  (
    .A(mgmt_io_in_unbuf[13]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[30] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[2]  (
    .A(mgmt_io_in_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[2] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[30]  (
    .A(\buf_in[30] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[31] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[31]  (
    .A(\buf_in[31] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[32] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[32]  (
    .A(\buf_in[32] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[33] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[33]  (
    .A(\buf_in[33] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[34] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[34]  (
    .A(\buf_in[34] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[34] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[35]  (
    .A(mgmt_io_in_unbuf[14]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[36] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[36]  (
    .A(\buf_in[36] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[37] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[37]  (
    .A(\buf_in[37] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[38] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[38]  (
    .A(\buf_in[38] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[39] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[39]  (
    .A(\buf_in[39] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[40] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[3]  (
    .A(mgmt_io_in_unbuf[3]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[3] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[40]  (
    .A(\buf_in[40] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[40] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[41]  (
    .A(mgmt_io_in_unbuf[15]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[42] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[42]  (
    .A(\buf_in[42] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[43] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[43]  (
    .A(\buf_in[43] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[44] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[44]  (
    .A(\buf_in[44] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[45] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[45]  (
    .A(\buf_in[45] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[45] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[46]  (
    .A(mgmt_io_in_unbuf[16]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[47] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[47]  (
    .A(\buf_in[47] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[48] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[48]  (
    .A(\buf_in[48] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[49] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[49]  (
    .A(\buf_in[49] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[50] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[4]  (
    .A(mgmt_io_in_unbuf[4]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[4] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[50]  (
    .A(\buf_in[50] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[50] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[51]  (
    .A(mgmt_io_in_unbuf[17]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[52] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[52]  (
    .A(\buf_in[52] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[53] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[53]  (
    .A(\buf_in[53] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[54] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[54]  (
    .A(\buf_in[54] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[54] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[55]  (
    .A(mgmt_io_in_unbuf[18]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[56] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[56]  (
    .A(\buf_in[56] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[57] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[57]  (
    .A(\buf_in[57] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[58] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[58]  (
    .A(\buf_in[58] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[58] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[59]  (
    .A(mgmt_io_in_unbuf[19]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[60] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[5]  (
    .A(mgmt_io_in_unbuf[5]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[5] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[60]  (
    .A(\buf_in[60] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[61] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[61]  (
    .A(\buf_in[61] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[62] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[62]  (
    .A(\buf_in[62] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[62] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[63]  (
    .A(mgmt_io_in_unbuf[20]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[64] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[64]  (
    .A(\buf_in[64] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[65] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[65]  (
    .A(\buf_in[65] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[66] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[66]  (
    .A(\buf_in[66] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[66] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[67]  (
    .A(mgmt_io_in_unbuf[21]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[68] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[68]  (
    .A(\buf_in[68] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[69] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[69]  (
    .A(\buf_in[69] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[70] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[6]  (
    .A(mgmt_io_in_unbuf[6]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[7] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[70]  (
    .A(\buf_in[70] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[70] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[71]  (
    .A(mgmt_io_in_unbuf[22]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[72] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[72]  (
    .A(\buf_in[72] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[73] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[73]  (
    .A(\buf_in[73] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[74] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[74]  (
    .A(\buf_in[74] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[74] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[75]  (
    .A(mgmt_io_in_unbuf[23]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[76] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[76]  (
    .A(\buf_in[76] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[77] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[77]  (
    .A(\buf_in[77] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[77] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[78]  (
    .A(mgmt_io_in_unbuf[24]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[79] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[79]  (
    .A(\buf_in[79] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[80] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[7]  (
    .A(\buf_in[7] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[7] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[80]  (
    .A(\buf_in[80] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[80] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[81]  (
    .A(mgmt_io_in_unbuf[25]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[82] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[82]  (
    .A(\buf_in[82] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[83] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[83]  (
    .A(\buf_in[83] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[83] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[84]  (
    .A(mgmt_io_in_unbuf[26]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[85] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[85]  (
    .A(\buf_in[85] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[86] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[86]  (
    .A(\buf_in[86] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[86] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[87]  (
    .A(mgmt_io_in_unbuf[27]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[88] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[88]  (
    .A(\buf_in[88] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[88] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[89]  (
    .A(mgmt_io_in_unbuf[28]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[90] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[8]  (
    .A(mgmt_io_in_unbuf[7]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[9] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[90]  (
    .A(\buf_in[90] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[90] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[91]  (
    .A(mgmt_io_in_unbuf[29]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[92] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[92]  (
    .A(\buf_in[92] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[92] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[93]  (
    .A(mgmt_io_in_unbuf[30]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[94] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[94]  (
    .A(\buf_in[94] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[94] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[95]  (
    .A(mgmt_io_out_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[95] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[96]  (
    .A(mgmt_io_out_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[96] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[97]  (
    .A(mgmt_io_out_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[97] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[98]  (
    .A(mgmt_io_out_unbuf[3]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[98] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[99]  (
    .A(mgmt_io_out_unbuf[4]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[99] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[9]  (
    .A(\buf_in[9] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[9] )
  );

  /* NOTE:  Hand-edited to insert the decap_12 cells	*/
  /* WARNING:  Hand-edited gate level netlist!		*/
  /* Fortunately, decap cells are trivial so the change	*/
  /* is pretty low-risk.				*/

  sky130_ef_sc_hd__decap_12 sigbuf_decaps [100:0] (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
  );

  /* End of hand-editing */

  assign \buf_out[192]  = \buf_in[193] ;
  assign \buf_out[190]  = \buf_in[191] ;
  assign \buf_out[188]  = \buf_in[189] ;
  assign \buf_out[186]  = \buf_in[187] ;
  assign \buf_out[184]  = \buf_in[185] ;
  assign \buf_out[182]  = \buf_in[183] ;
  assign \buf_out[180]  = \buf_in[181] ;
  assign \buf_out[179]  = \buf_in[180] ;
  assign \buf_out[177]  = \buf_in[178] ;
  assign \buf_out[176]  = \buf_in[177] ;
  assign \buf_out[174]  = \buf_in[175] ;
  assign \buf_out[173]  = \buf_in[174] ;
  assign \buf_out[171]  = \buf_in[172] ;
  assign \buf_out[170]  = \buf_in[171] ;
  assign \buf_out[168]  = \buf_in[169] ;
  assign \buf_out[167]  = \buf_in[168] ;
  assign \buf_out[166]  = \buf_in[167] ;
  assign \buf_out[164]  = \buf_in[165] ;
  assign \buf_out[163]  = \buf_in[164] ;
  assign \buf_out[162]  = \buf_in[163] ;
  assign \buf_out[160]  = \buf_in[161] ;
  assign \buf_out[159]  = \buf_in[160] ;
  assign \buf_out[158]  = \buf_in[159] ;
  assign \buf_out[156]  = \buf_in[157] ;
  assign \buf_out[155]  = \buf_in[156] ;
  assign \buf_out[154]  = \buf_in[155] ;
  assign \buf_out[152]  = \buf_in[153] ;
  assign \buf_out[151]  = \buf_in[152] ;
  assign \buf_out[150]  = \buf_in[151] ;
  assign \buf_out[148]  = \buf_in[149] ;
  assign \buf_out[147]  = \buf_in[148] ;
  assign \buf_out[146]  = \buf_in[147] ;
  assign \buf_out[144]  = \buf_in[145] ;
  assign \buf_out[143]  = \buf_in[144] ;
  assign \buf_out[142]  = \buf_in[143] ;
  assign \buf_out[141]  = \buf_in[142] ;
  assign \buf_out[139]  = \buf_in[140] ;
  assign \buf_out[138]  = \buf_in[139] ;
  assign \buf_out[137]  = \buf_in[138] ;
  assign \buf_out[136]  = \buf_in[137] ;
  assign \buf_out[134]  = \buf_in[135] ;
  assign \buf_out[133]  = \buf_in[134] ;
  assign \buf_out[132]  = \buf_in[133] ;
  assign \buf_out[131]  = \buf_in[132] ;
  assign \buf_out[130]  = \buf_in[131] ;
  assign \buf_out[128]  = \buf_in[129] ;
  assign \buf_out[127]  = \buf_in[128] ;
  assign \buf_out[126]  = \buf_in[127] ;
  assign \buf_out[125]  = \buf_in[126] ;
  assign \buf_out[124]  = \buf_in[125] ;
  assign \buf_out[122]  = \buf_in[123] ;
  assign \buf_out[121]  = \buf_in[122] ;
  assign \buf_out[120]  = \buf_in[121] ;
  assign \buf_out[119]  = \buf_in[120] ;
  assign \buf_out[118]  = \buf_in[119] ;
  assign \buf_out[116]  = \buf_in[117] ;
  assign \buf_out[115]  = \buf_in[116] ;
  assign \buf_out[114]  = \buf_in[115] ;
  assign \buf_out[112]  = \buf_in[113] ;
  assign \buf_out[111]  = \buf_in[112] ;
  assign \buf_out[109]  = \buf_in[110] ;
  assign \buf_out[108]  = \buf_in[109] ;
  assign \buf_out[106]  = \buf_in[107] ;
  assign \buf_out[105]  = \buf_in[106] ;
  assign \buf_out[103]  = \buf_in[104] ;
  assign \buf_out[101]  = \buf_in[102] ;
  assign \buf_out[93]  = \buf_in[94] ;
  assign \buf_out[91]  = \buf_in[92] ;
  assign \buf_out[89]  = \buf_in[90] ;
  assign \buf_out[87]  = \buf_in[88] ;
  assign \buf_out[85]  = \buf_in[86] ;
  assign \buf_out[84]  = \buf_in[85] ;
  assign \buf_out[82]  = \buf_in[83] ;
  assign \buf_out[81]  = \buf_in[82] ;
  assign \buf_out[79]  = \buf_in[80] ;
  assign \buf_out[78]  = \buf_in[79] ;
  assign \buf_out[76]  = \buf_in[77] ;
  assign \buf_out[75]  = \buf_in[76] ;
  assign \buf_out[73]  = \buf_in[74] ;
  assign \buf_out[72]  = \buf_in[73] ;
  assign \buf_out[71]  = \buf_in[72] ;
  assign \buf_out[69]  = \buf_in[70] ;
  assign \buf_out[68]  = \buf_in[69] ;
  assign \buf_out[67]  = \buf_in[68] ;
  assign \buf_out[65]  = \buf_in[66] ;
  assign \buf_out[64]  = \buf_in[65] ;
  assign \buf_out[63]  = \buf_in[64] ;
  assign \buf_out[61]  = \buf_in[62] ;
  assign \buf_out[60]  = \buf_in[61] ;
  assign \buf_out[59]  = \buf_in[60] ;
  assign \buf_out[57]  = \buf_in[58] ;
  assign \buf_out[56]  = \buf_in[57] ;
  assign \buf_out[55]  = \buf_in[56] ;
  assign \buf_out[53]  = \buf_in[54] ;
  assign \buf_out[52]  = \buf_in[53] ;
  assign \buf_out[51]  = \buf_in[52] ;
  assign \buf_out[49]  = \buf_in[50] ;
  assign \buf_out[48]  = \buf_in[49] ;
  assign \buf_out[47]  = \buf_in[48] ;
  assign \buf_out[46]  = \buf_in[47] ;
  assign \buf_out[44]  = \buf_in[45] ;
  assign \buf_out[43]  = \buf_in[44] ;
  assign \buf_out[42]  = \buf_in[43] ;
  assign \buf_out[41]  = \buf_in[42] ;
  assign \buf_out[39]  = \buf_in[40] ;
  assign \buf_out[38]  = \buf_in[39] ;
  assign \buf_out[37]  = \buf_in[38] ;
  assign \buf_out[36]  = \buf_in[37] ;
  assign \buf_out[35]  = \buf_in[36] ;
  assign \buf_out[33]  = \buf_in[34] ;
  assign \buf_out[32]  = \buf_in[33] ;
  assign \buf_out[31]  = \buf_in[32] ;
  assign \buf_out[30]  = \buf_in[31] ;
  assign \buf_out[29]  = \buf_in[30] ;
  assign \buf_out[27]  = \buf_in[28] ;
  assign \buf_out[26]  = \buf_in[27] ;
  assign \buf_out[25]  = \buf_in[26] ;
  assign \buf_out[24]  = \buf_in[25] ;
  assign \buf_out[23]  = \buf_in[24] ;
  assign \buf_out[21]  = \buf_in[22] ;
  assign \buf_out[20]  = \buf_in[21] ;
  assign \buf_out[19]  = \buf_in[20] ;
  assign \buf_out[17]  = \buf_in[18] ;
  assign \buf_out[16]  = \buf_in[17] ;
  assign \buf_out[14]  = \buf_in[15] ;
  assign \buf_out[13]  = \buf_in[14] ;
  assign \buf_out[11]  = \buf_in[12] ;
  assign \buf_out[10]  = \buf_in[11] ;
  assign \buf_out[8]  = \buf_in[9] ;
  assign \buf_out[6]  = \buf_in[7] ;
  assign \buf_in[194]  = mgmt_io_oeb_unbuf[2];
  assign \buf_in[192]  = mgmt_io_oeb_unbuf[1];
  assign \buf_in[190]  = mgmt_io_oeb_unbuf[0];
  assign \buf_in[188]  = mgmt_io_out_unbuf[30];
  assign \buf_in[186]  = mgmt_io_out_unbuf[29];
  assign \buf_in[184]  = mgmt_io_out_unbuf[28];
  assign \buf_in[182]  = mgmt_io_out_unbuf[27];
  assign \buf_in[179]  = mgmt_io_out_unbuf[26];
  assign \buf_in[176]  = mgmt_io_out_unbuf[25];
  assign \buf_in[173]  = mgmt_io_out_unbuf[24];
  assign \buf_in[170]  = mgmt_io_out_unbuf[23];
  assign \buf_in[166]  = mgmt_io_out_unbuf[22];
  assign \buf_in[162]  = mgmt_io_out_unbuf[21];
  assign \buf_in[158]  = mgmt_io_out_unbuf[20];
  assign \buf_in[154]  = mgmt_io_out_unbuf[19];
  assign \buf_in[150]  = mgmt_io_out_unbuf[18];
  assign \buf_in[146]  = mgmt_io_out_unbuf[17];
  assign \buf_in[141]  = mgmt_io_out_unbuf[16];
  assign \buf_in[136]  = mgmt_io_out_unbuf[15];
  assign \buf_in[130]  = mgmt_io_out_unbuf[14];
  assign \buf_in[124]  = mgmt_io_out_unbuf[13];
  assign \buf_in[118]  = mgmt_io_out_unbuf[12];
  assign \buf_in[114]  = mgmt_io_out_unbuf[11];
  assign \buf_in[111]  = mgmt_io_out_unbuf[10];
  assign \buf_in[108]  = mgmt_io_out_unbuf[9];
  assign \buf_in[105]  = mgmt_io_out_unbuf[8];
  assign \buf_in[103]  = mgmt_io_out_unbuf[7];
  assign \buf_in[101]  = mgmt_io_out_unbuf[6];
  assign \buf_in[100]  = mgmt_io_out_unbuf[5];
  assign \buf_in[99]  = mgmt_io_out_unbuf[4];
  assign \buf_in[98]  = mgmt_io_out_unbuf[3];
  assign \buf_in[97]  = mgmt_io_out_unbuf[2];
  assign \buf_in[96]  = mgmt_io_out_unbuf[1];
  assign \buf_in[95]  = mgmt_io_out_unbuf[0];
  assign \buf_in[93]  = mgmt_io_in_unbuf[30];
  assign \buf_in[91]  = mgmt_io_in_unbuf[29];
  assign \buf_in[89]  = mgmt_io_in_unbuf[28];
  assign \buf_in[87]  = mgmt_io_in_unbuf[27];
  assign \buf_in[84]  = mgmt_io_in_unbuf[26];
  assign \buf_in[81]  = mgmt_io_in_unbuf[25];
  assign \buf_in[78]  = mgmt_io_in_unbuf[24];
  assign \buf_in[75]  = mgmt_io_in_unbuf[23];
  assign \buf_in[71]  = mgmt_io_in_unbuf[22];
  assign \buf_in[67]  = mgmt_io_in_unbuf[21];
  assign \buf_in[63]  = mgmt_io_in_unbuf[20];
  assign \buf_in[59]  = mgmt_io_in_unbuf[19];
  assign \buf_in[55]  = mgmt_io_in_unbuf[18];
  assign \buf_in[51]  = mgmt_io_in_unbuf[17];
  assign \buf_in[46]  = mgmt_io_in_unbuf[16];
  assign \buf_in[41]  = mgmt_io_in_unbuf[15];
  assign \buf_in[35]  = mgmt_io_in_unbuf[14];
  assign \buf_in[29]  = mgmt_io_in_unbuf[13];
  assign \buf_in[23]  = mgmt_io_in_unbuf[12];
  assign \buf_in[19]  = mgmt_io_in_unbuf[11];
  assign \buf_in[16]  = mgmt_io_in_unbuf[10];
  assign \buf_in[13]  = mgmt_io_in_unbuf[9];
  assign \buf_in[10]  = mgmt_io_in_unbuf[8];
  assign \buf_in[8]  = mgmt_io_in_unbuf[7];
  assign \buf_in[6]  = mgmt_io_in_unbuf[6];
  assign \buf_in[5]  = mgmt_io_in_unbuf[5];
  assign \buf_in[4]  = mgmt_io_in_unbuf[4];
  assign \buf_in[3]  = mgmt_io_in_unbuf[3];
  assign \buf_in[2]  = mgmt_io_in_unbuf[2];
  assign \buf_in[1]  = mgmt_io_in_unbuf[1];
  assign \buf_in[0]  = mgmt_io_in_unbuf[0];
  assign \buf_out[194]  = \buf_in[195] ;
  assign mgmt_io_out_buf = { \buf_out[189] , \buf_out[187] , \buf_out[185] , \buf_out[183] , \buf_out[181] , \buf_out[178] , \buf_out[175] , \buf_out[172] , \buf_out[169] , \buf_out[165] , \buf_out[161] , \buf_out[157] , \buf_out[153] , \buf_out[149] , \buf_out[145] , \buf_out[140] , \buf_out[135] , \buf_out[129] , \buf_out[123] , \buf_out[117] , \buf_out[113] , \buf_out[110] , \buf_out[107] , \buf_out[104] , \buf_out[102] , \buf_out[100] , \buf_out[99] , \buf_out[98] , \buf_out[97] , \buf_out[96] , \buf_out[95]  };
  assign mgmt_io_in_buf = { \buf_out[94] , \buf_out[92] , \buf_out[90] , \buf_out[88] , \buf_out[86] , \buf_out[83] , \buf_out[80] , \buf_out[77] , \buf_out[74] , \buf_out[70] , \buf_out[66] , \buf_out[62] , \buf_out[58] , \buf_out[54] , \buf_out[50] , \buf_out[45] , \buf_out[40] , \buf_out[34] , \buf_out[28] , \buf_out[22] , \buf_out[18] , \buf_out[15] , \buf_out[12] , \buf_out[9] , \buf_out[7] , \buf_out[5] , \buf_out[4] , \buf_out[3] , \buf_out[2] , \buf_out[1] , \buf_out[0]  };
  assign mgmt_io_oeb_buf = { \buf_out[195] , \buf_out[193] , \buf_out[191]  };
endmodule
