/* Generated by Yosys 0.20+70 (git sha1 6e907acf86d, gcc 8.3.1 -fPIC -Os) */

module gpio_signal_buffering_alt(vccd, vssd, mgmt_io_in_unbuf, mgmt_io_out_unbuf, mgmt_io_oeb_buf, mgmt_io_in_buf, mgmt_io_out_buf, mgmt_io_oeb_unbuf);
  wire \buf_in[0] ;
  wire \buf_in[100] ;
  wire \buf_in[101] ;
  wire \buf_in[10] ;
  wire \buf_in[11] ;
  wire \buf_in[12] ;
  wire \buf_in[13] ;
  wire \buf_in[14] ;
  wire \buf_in[15] ;
  wire \buf_in[16] ;
  wire \buf_in[17] ;
  wire \buf_in[18] ;
  wire \buf_in[19] ;
  wire \buf_in[1] ;
  wire \buf_in[20] ;
  wire \buf_in[21] ;
  wire \buf_in[22] ;
  wire \buf_in[23] ;
  wire \buf_in[24] ;
  wire \buf_in[25] ;
  wire \buf_in[26] ;
  wire \buf_in[27] ;
  wire \buf_in[28] ;
  wire \buf_in[29] ;
  wire \buf_in[2] ;
  wire \buf_in[30] ;
  wire \buf_in[31] ;
  wire \buf_in[32] ;
  wire \buf_in[33] ;
  wire \buf_in[34] ;
  wire \buf_in[35] ;
  wire \buf_in[36] ;
  wire \buf_in[37] ;
  wire \buf_in[38] ;
  wire \buf_in[39] ;
  wire \buf_in[3] ;
  wire \buf_in[40] ;
  wire \buf_in[41] ;
  wire \buf_in[42] ;
  wire \buf_in[43] ;
  wire \buf_in[44] ;
  wire \buf_in[45] ;
  wire \buf_in[46] ;
  wire \buf_in[47] ;
  wire \buf_in[48] ;
  wire \buf_in[49] ;
  wire \buf_in[4] ;
  wire \buf_in[50] ;
  wire \buf_in[51] ;
  wire \buf_in[52] ;
  wire \buf_in[53] ;
  wire \buf_in[54] ;
  wire \buf_in[55] ;
  wire \buf_in[56] ;
  wire \buf_in[57] ;
  wire \buf_in[58] ;
  wire \buf_in[59] ;
  wire \buf_in[5] ;
  wire \buf_in[60] ;
  wire \buf_in[61] ;
  wire \buf_in[62] ;
  wire \buf_in[63] ;
  wire \buf_in[64] ;
  wire \buf_in[65] ;
  wire \buf_in[66] ;
  wire \buf_in[67] ;
  wire \buf_in[68] ;
  wire \buf_in[69] ;
  wire \buf_in[6] ;
  wire \buf_in[70] ;
  wire \buf_in[71] ;
  wire \buf_in[72] ;
  wire \buf_in[73] ;
  wire \buf_in[74] ;
  wire \buf_in[75] ;
  wire \buf_in[76] ;
  wire \buf_in[77] ;
  wire \buf_in[78] ;
  wire \buf_in[79] ;
  wire \buf_in[7] ;
  wire \buf_in[80] ;
  wire \buf_in[81] ;
  wire \buf_in[82] ;
  wire \buf_in[83] ;
  wire \buf_in[84] ;
  wire \buf_in[85] ;
  wire \buf_in[86] ;
  wire \buf_in[87] ;
  wire \buf_in[88] ;
  wire \buf_in[89] ;
  wire \buf_in[8] ;
  wire \buf_in[90] ;
  wire \buf_in[91] ;
  wire \buf_in[92] ;
  wire \buf_in[93] ;
  wire \buf_in[94] ;
  wire \buf_in[95] ;
  wire \buf_in[96] ;
  wire \buf_in[97] ;
  wire \buf_in[98] ;
  wire \buf_in[99] ;
  wire \buf_in[9] ;
  wire \buf_out[0] ;
  wire \buf_out[100] ;
  wire \buf_out[101] ;
  wire \buf_out[10] ;
  wire \buf_out[11] ;
  wire \buf_out[12] ;
  wire \buf_out[13] ;
  wire \buf_out[14] ;
  wire \buf_out[15] ;
  wire \buf_out[16] ;
  wire \buf_out[17] ;
  wire \buf_out[18] ;
  wire \buf_out[19] ;
  wire \buf_out[1] ;
  wire \buf_out[20] ;
  wire \buf_out[21] ;
  wire \buf_out[22] ;
  wire \buf_out[23] ;
  wire \buf_out[24] ;
  wire \buf_out[25] ;
  wire \buf_out[26] ;
  wire \buf_out[27] ;
  wire \buf_out[28] ;
  wire \buf_out[29] ;
  wire \buf_out[2] ;
  wire \buf_out[30] ;
  wire \buf_out[31] ;
  wire \buf_out[32] ;
  wire \buf_out[33] ;
  wire \buf_out[34] ;
  wire \buf_out[35] ;
  wire \buf_out[36] ;
  wire \buf_out[37] ;
  wire \buf_out[38] ;
  wire \buf_out[39] ;
  wire \buf_out[3] ;
  wire \buf_out[40] ;
  wire \buf_out[41] ;
  wire \buf_out[42] ;
  wire \buf_out[43] ;
  wire \buf_out[44] ;
  wire \buf_out[45] ;
  wire \buf_out[46] ;
  wire \buf_out[47] ;
  wire \buf_out[48] ;
  wire \buf_out[49] ;
  wire \buf_out[4] ;
  wire \buf_out[50] ;
  wire \buf_out[51] ;
  wire \buf_out[52] ;
  wire \buf_out[53] ;
  wire \buf_out[54] ;
  wire \buf_out[55] ;
  wire \buf_out[56] ;
  wire \buf_out[57] ;
  wire \buf_out[58] ;
  wire \buf_out[59] ;
  wire \buf_out[5] ;
  wire \buf_out[60] ;
  wire \buf_out[61] ;
  wire \buf_out[62] ;
  wire \buf_out[63] ;
  wire \buf_out[64] ;
  wire \buf_out[65] ;
  wire \buf_out[66] ;
  wire \buf_out[67] ;
  wire \buf_out[68] ;
  wire \buf_out[69] ;
  wire \buf_out[6] ;
  wire \buf_out[70] ;
  wire \buf_out[71] ;
  wire \buf_out[72] ;
  wire \buf_out[73] ;
  wire \buf_out[74] ;
  wire \buf_out[75] ;
  wire \buf_out[76] ;
  wire \buf_out[77] ;
  wire \buf_out[78] ;
  wire \buf_out[79] ;
  wire \buf_out[7] ;
  wire \buf_out[80] ;
  wire \buf_out[81] ;
  wire \buf_out[82] ;
  wire \buf_out[83] ;
  wire \buf_out[84] ;
  wire \buf_out[85] ;
  wire \buf_out[86] ;
  wire \buf_out[87] ;
  wire \buf_out[88] ;
  wire \buf_out[89] ;
  wire \buf_out[8] ;
  wire \buf_out[90] ;
  wire \buf_out[91] ;
  wire \buf_out[92] ;
  wire \buf_out[93] ;
  wire \buf_out[94] ;
  wire \buf_out[95] ;
  wire \buf_out[96] ;
  wire \buf_out[97] ;
  wire \buf_out[98] ;
  wire \buf_out[99] ;
  wire \buf_out[9] ;
  output [19:0] mgmt_io_in_buf;
  wire [19:0] mgmt_io_in_buf;
  input [19:0] mgmt_io_in_unbuf;
  wire [19:0] mgmt_io_in_unbuf;
  output [2:0] mgmt_io_oeb_buf;
  wire [2:0] mgmt_io_oeb_buf;
  input [2:0] mgmt_io_oeb_unbuf;
  wire [2:0] mgmt_io_oeb_unbuf;
  output [19:0] mgmt_io_out_buf;
  wire [19:0] mgmt_io_out_buf;
  input [19:0] mgmt_io_out_unbuf;
  wire [19:0] mgmt_io_out_unbuf;
  input vccd;
  wire vccd;
  input vssd;
  wire vssd;
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[0]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[10]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[11]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[12]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[13]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[14]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[15]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[16]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[17]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[18]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[19]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[1]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[20]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[21]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[22]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[23]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[24]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[25]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[26]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[27]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[28]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[29]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[2]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[30]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[31]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[32]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[33]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[34]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[35]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[36]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[37]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[38]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[39]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[3]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[40]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[41]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[42]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[43]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[44]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[45]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[46]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[47]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[48]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[49]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[4]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[50]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[51]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[52]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[53]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[54]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[55]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[56]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[57]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[58]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[59]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[5]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[6]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[7]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[8]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_ef_sc_hd__decap_12 \sigbuf_decaps[9]  (
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[0]  (
    .A(mgmt_io_in_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[0] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[100]  (
    .A(mgmt_io_oeb_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[101] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[101]  (
    .A(\buf_in[101] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[101] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[10]  (
    .A(\buf_in[10] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[11] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[11]  (
    .A(\buf_in[11] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[11] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[12]  (
    .A(mgmt_io_in_unbuf[8]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[13] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[13]  (
    .A(\buf_in[13] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[14] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[14]  (
    .A(\buf_in[14] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[15] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[15]  (
    .A(\buf_in[15] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[15] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[16]  (
    .A(mgmt_io_in_unbuf[9]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[17] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[17]  (
    .A(\buf_in[17] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[18] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[18]  (
    .A(\buf_in[18] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[19] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[19]  (
    .A(\buf_in[19] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[19] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[1]  (
    .A(mgmt_io_in_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[1] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[20]  (
    .A(mgmt_io_in_unbuf[10]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[21] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[21]  (
    .A(\buf_in[21] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[22] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[22]  (
    .A(\buf_in[22] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[23] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[23]  (
    .A(\buf_in[23] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[23] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[24]  (
    .A(mgmt_io_in_unbuf[11]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[25] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[25]  (
    .A(\buf_in[25] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[26] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[26]  (
    .A(\buf_in[26] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[27] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[27]  (
    .A(\buf_in[27] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[27] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[28]  (
    .A(mgmt_io_in_unbuf[12]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[29] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[29]  (
    .A(\buf_in[29] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[30] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[2]  (
    .A(mgmt_io_in_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[2] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[30]  (
    .A(\buf_in[30] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[30] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[31]  (
    .A(mgmt_io_in_unbuf[13]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[32] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[32]  (
    .A(\buf_in[32] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[33] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[33]  (
    .A(\buf_in[33] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[33] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[34]  (
    .A(mgmt_io_in_unbuf[14]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[35] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[35]  (
    .A(\buf_in[35] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[36] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[36]  (
    .A(\buf_in[36] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[36] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[37]  (
    .A(mgmt_io_in_unbuf[15]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[38] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[38]  (
    .A(\buf_in[38] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[39] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[39]  (
    .A(\buf_in[39] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[39] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[3]  (
    .A(mgmt_io_in_unbuf[3]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[3] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[40]  (
    .A(mgmt_io_in_unbuf[16]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[41] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[41]  (
    .A(\buf_in[41] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[41] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[42]  (
    .A(mgmt_io_in_unbuf[17]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[43] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[43]  (
    .A(\buf_in[43] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[43] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[44]  (
    .A(mgmt_io_in_unbuf[18]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[45] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[45]  (
    .A(\buf_in[45] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[45] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[46]  (
    .A(mgmt_io_in_unbuf[19]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[47] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[47]  (
    .A(\buf_in[47] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[47] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[48]  (
    .A(mgmt_io_out_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[48] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[49]  (
    .A(mgmt_io_out_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[49] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[4]  (
    .A(mgmt_io_in_unbuf[4]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[4] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[50]  (
    .A(mgmt_io_out_unbuf[2]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[50] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[51]  (
    .A(mgmt_io_out_unbuf[3]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[51] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[52]  (
    .A(mgmt_io_out_unbuf[4]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[52] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[53]  (
    .A(mgmt_io_out_unbuf[5]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[53] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[54]  (
    .A(mgmt_io_out_unbuf[6]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[55] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[55]  (
    .A(\buf_in[55] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[55] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[56]  (
    .A(mgmt_io_out_unbuf[7]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[57] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[57]  (
    .A(\buf_in[57] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[58] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[58]  (
    .A(\buf_in[58] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[59] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[59]  (
    .A(\buf_in[59] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[59] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[5]  (
    .A(mgmt_io_in_unbuf[5]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[5] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[60]  (
    .A(mgmt_io_out_unbuf[8]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[61] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[61]  (
    .A(\buf_in[61] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[62] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[62]  (
    .A(\buf_in[62] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[63] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[63]  (
    .A(\buf_in[63] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[63] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[64]  (
    .A(mgmt_io_out_unbuf[9]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[65] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[65]  (
    .A(\buf_in[65] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[66] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[66]  (
    .A(\buf_in[66] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[67] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[67]  (
    .A(\buf_in[67] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[67] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[68]  (
    .A(mgmt_io_out_unbuf[10]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[69] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[69]  (
    .A(\buf_in[69] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[70] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[6]  (
    .A(mgmt_io_in_unbuf[6]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[7] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[70]  (
    .A(\buf_in[70] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[71] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[71]  (
    .A(\buf_in[71] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[71] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[72]  (
    .A(mgmt_io_out_unbuf[11]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[73] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[73]  (
    .A(\buf_in[73] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[74] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[74]  (
    .A(\buf_in[74] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[75] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[75]  (
    .A(\buf_in[75] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[75] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[76]  (
    .A(mgmt_io_out_unbuf[12]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[77] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[77]  (
    .A(\buf_in[77] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[78] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[78]  (
    .A(\buf_in[78] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[78] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[79]  (
    .A(mgmt_io_out_unbuf[13]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[80] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[7]  (
    .A(\buf_in[7] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[7] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[80]  (
    .A(\buf_in[80] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[81] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[81]  (
    .A(\buf_in[81] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[81] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[82]  (
    .A(mgmt_io_out_unbuf[14]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[83] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[83]  (
    .A(\buf_in[83] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[84] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[84]  (
    .A(\buf_in[84] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[84] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[85]  (
    .A(mgmt_io_out_unbuf[15]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[86] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[86]  (
    .A(\buf_in[86] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[87] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[87]  (
    .A(\buf_in[87] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[87] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[88]  (
    .A(mgmt_io_out_unbuf[16]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[89] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[89]  (
    .A(\buf_in[89] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[89] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[8]  (
    .A(mgmt_io_in_unbuf[7]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[9] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[90]  (
    .A(mgmt_io_out_unbuf[17]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[91] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[91]  (
    .A(\buf_in[91] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[91] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[92]  (
    .A(mgmt_io_out_unbuf[18]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[93] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[93]  (
    .A(\buf_in[93] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[93] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[94]  (
    .A(mgmt_io_out_unbuf[19]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[95] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[95]  (
    .A(\buf_in[95] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[95] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[96]  (
    .A(mgmt_io_oeb_unbuf[0]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[97] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[97]  (
    .A(\buf_in[97] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[97] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[98]  (
    .A(mgmt_io_oeb_unbuf[1]),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[99] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[99]  (
    .A(\buf_in[99] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_out[99] )
  );
  sky130_fd_sc_hd__buf_8 \signal_buffers[9]  (
    .A(\buf_in[9] ),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .X(\buf_in[10] )
  );
  assign \buf_in[98]  = mgmt_io_oeb_unbuf[1];
  assign \buf_in[96]  = mgmt_io_oeb_unbuf[0];
  assign \buf_in[94]  = mgmt_io_out_unbuf[19];
  assign \buf_in[92]  = mgmt_io_out_unbuf[18];
  assign \buf_in[90]  = mgmt_io_out_unbuf[17];
  assign \buf_in[88]  = mgmt_io_out_unbuf[16];
  assign \buf_in[85]  = mgmt_io_out_unbuf[15];
  assign \buf_in[82]  = mgmt_io_out_unbuf[14];
  assign \buf_in[79]  = mgmt_io_out_unbuf[13];
  assign \buf_in[76]  = mgmt_io_out_unbuf[12];
  assign \buf_in[72]  = mgmt_io_out_unbuf[11];
  assign \buf_in[68]  = mgmt_io_out_unbuf[10];
  assign \buf_in[64]  = mgmt_io_out_unbuf[9];
  assign \buf_in[60]  = mgmt_io_out_unbuf[8];
  assign \buf_in[56]  = mgmt_io_out_unbuf[7];
  assign \buf_in[54]  = mgmt_io_out_unbuf[6];
  assign \buf_in[53]  = mgmt_io_out_unbuf[5];
  assign \buf_in[52]  = mgmt_io_out_unbuf[4];
  assign \buf_in[51]  = mgmt_io_out_unbuf[3];
  assign \buf_in[50]  = mgmt_io_out_unbuf[2];
  assign \buf_in[49]  = mgmt_io_out_unbuf[1];
  assign \buf_in[48]  = mgmt_io_out_unbuf[0];
  assign \buf_in[46]  = mgmt_io_in_unbuf[19];
  assign \buf_in[44]  = mgmt_io_in_unbuf[18];
  assign \buf_in[42]  = mgmt_io_in_unbuf[17];
  assign \buf_in[40]  = mgmt_io_in_unbuf[16];
  assign \buf_in[37]  = mgmt_io_in_unbuf[15];
  assign \buf_in[34]  = mgmt_io_in_unbuf[14];
  assign \buf_in[31]  = mgmt_io_in_unbuf[13];
  assign \buf_in[28]  = mgmt_io_in_unbuf[12];
  assign \buf_in[24]  = mgmt_io_in_unbuf[11];
  assign \buf_in[20]  = mgmt_io_in_unbuf[10];
  assign \buf_in[16]  = mgmt_io_in_unbuf[9];
  assign \buf_in[12]  = mgmt_io_in_unbuf[8];
  assign \buf_in[8]  = mgmt_io_in_unbuf[7];
  assign \buf_in[6]  = mgmt_io_in_unbuf[6];
  assign \buf_in[5]  = mgmt_io_in_unbuf[5];
  assign \buf_in[4]  = mgmt_io_in_unbuf[4];
  assign \buf_in[3]  = mgmt_io_in_unbuf[3];
  assign \buf_in[2]  = mgmt_io_in_unbuf[2];
  assign \buf_in[1]  = mgmt_io_in_unbuf[1];
  assign \buf_in[0]  = mgmt_io_in_unbuf[0];
  assign \buf_out[100]  = \buf_in[101] ;
  assign \buf_out[98]  = \buf_in[99] ;
  assign \buf_out[96]  = \buf_in[97] ;
  assign \buf_out[94]  = \buf_in[95] ;
  assign \buf_out[92]  = \buf_in[93] ;
  assign \buf_out[90]  = \buf_in[91] ;
  assign \buf_out[88]  = \buf_in[89] ;
  assign \buf_out[86]  = \buf_in[87] ;
  assign \buf_out[85]  = \buf_in[86] ;
  assign \buf_out[83]  = \buf_in[84] ;
  assign \buf_out[82]  = \buf_in[83] ;
  assign \buf_out[80]  = \buf_in[81] ;
  assign \buf_out[79]  = \buf_in[80] ;
  assign \buf_out[77]  = \buf_in[78] ;
  assign \buf_out[76]  = \buf_in[77] ;
  assign \buf_out[74]  = \buf_in[75] ;
  assign \buf_out[73]  = \buf_in[74] ;
  assign \buf_out[72]  = \buf_in[73] ;
  assign \buf_out[70]  = \buf_in[71] ;
  assign \buf_out[69]  = \buf_in[70] ;
  assign \buf_out[68]  = \buf_in[69] ;
  assign \buf_out[66]  = \buf_in[67] ;
  assign \buf_out[65]  = \buf_in[66] ;
  assign \buf_out[64]  = \buf_in[65] ;
  assign \buf_out[62]  = \buf_in[63] ;
  assign \buf_out[61]  = \buf_in[62] ;
  assign \buf_out[60]  = \buf_in[61] ;
  assign \buf_out[58]  = \buf_in[59] ;
  assign \buf_out[57]  = \buf_in[58] ;
  assign \buf_out[56]  = \buf_in[57] ;
  assign \buf_out[54]  = \buf_in[55] ;
  assign \buf_out[46]  = \buf_in[47] ;
  assign \buf_out[44]  = \buf_in[45] ;
  assign \buf_out[42]  = \buf_in[43] ;
  assign \buf_out[40]  = \buf_in[41] ;
  assign \buf_out[38]  = \buf_in[39] ;
  assign \buf_out[37]  = \buf_in[38] ;
  assign \buf_out[35]  = \buf_in[36] ;
  assign \buf_out[34]  = \buf_in[35] ;
  assign \buf_out[32]  = \buf_in[33] ;
  assign \buf_out[31]  = \buf_in[32] ;
  assign \buf_out[29]  = \buf_in[30] ;
  assign \buf_out[28]  = \buf_in[29] ;
  assign \buf_out[26]  = \buf_in[27] ;
  assign \buf_out[25]  = \buf_in[26] ;
  assign \buf_out[24]  = \buf_in[25] ;
  assign \buf_out[22]  = \buf_in[23] ;
  assign \buf_out[21]  = \buf_in[22] ;
  assign \buf_out[20]  = \buf_in[21] ;
  assign \buf_out[18]  = \buf_in[19] ;
  assign \buf_out[17]  = \buf_in[18] ;
  assign \buf_out[16]  = \buf_in[17] ;
  assign \buf_out[14]  = \buf_in[15] ;
  assign \buf_out[13]  = \buf_in[14] ;
  assign \buf_out[12]  = \buf_in[13] ;
  assign \buf_out[10]  = \buf_in[11] ;
  assign \buf_out[9]  = \buf_in[10] ;
  assign \buf_out[8]  = \buf_in[9] ;
  assign \buf_out[6]  = \buf_in[7] ;
  assign \buf_in[100]  = mgmt_io_oeb_unbuf[2];
  assign mgmt_io_out_buf = { \buf_out[95] , \buf_out[93] , \buf_out[91] , \buf_out[89] , \buf_out[87] , \buf_out[84] , \buf_out[81] , \buf_out[78] , \buf_out[75] , \buf_out[71] , \buf_out[67] , \buf_out[63] , \buf_out[59] , \buf_out[55] , \buf_out[53] , \buf_out[52] , \buf_out[51] , \buf_out[50] , \buf_out[49] , \buf_out[48]  };
  assign mgmt_io_in_buf = { \buf_out[47] , \buf_out[45] , \buf_out[43] , \buf_out[41] , \buf_out[39] , \buf_out[36] , \buf_out[33] , \buf_out[30] , \buf_out[27] , \buf_out[23] , \buf_out[19] , \buf_out[15] , \buf_out[11] , \buf_out[7] , \buf_out[5] , \buf_out[4] , \buf_out[3] , \buf_out[2] , \buf_out[1] , \buf_out[0]  };
  assign mgmt_io_oeb_buf = { \buf_out[101] , \buf_out[99] , \buf_out[97]  };
endmodule
